export enum UserRoleType {
  HR_ADMIN = 'hr_admin',
  EMPLOYEE = 'employee',
  IT_ADMIN = 'it_admin',
  IT_TEAM = 'IT_Team',
  MANAGER = 'manager',
  TEAM_LEAD = 'team_lead',
  IT_MANAGER = 'it_manager',
  IT_EMPLOYEE = 'it_employee',
  MENTOR = 'mentor',
  PROJECT_MANAGEMENT = 'account_manager',
  SUPER_ADMIN = 'Super_Admin',
  OPERATIONS_MANAGER = 'operations_manager',
  DESIGN_TEAM_LEAD = 'design_team_lead',
}
